version: 0.0
os: linux
files:
  - source: python.py
    destination: /home/ubuntu/app
    overwrite: true
hooks:
  ApplicationStart:
    - location: scrips/run_app.sh
      timeout: 60
      runas: ubuntu
